name: test
on:
  pull_request:
  push:
    branches:
      - main


jobs:
  test:
    name: build and test ros_typedb pkg
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: humble
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: ros_typedb
          target-ros2-distro: humble
